name: MenuItems
modelClass: Kevinklonne\MenuBuilder\Models\MenuItem
form: $/kevinklonne/menubuilder/models/menuitem/fields.yaml
design:
    displayMode: popup
    size: 700
defaultRedirect: kevinklonne/menubuilder/menuitems
create:
    title: 'kevinklonne.menubuilder::lang.menuitem.create'
    redirect: 'kevinklonne/menubuilder/menuitems/update/:id'
    redirectClose: kevinklonne/menubuilder/menuitems
update:
    title: 'kevinklonne.menubuilder::lang.menuitem.update'
    redirect: kevinklonne/menubuilder/menuitems
    redirectClose: kevinklonne/menubuilder/menuitems
