list: $/kevinklonne/menubuilder/models/menu/columns.yaml
modelClass: Kevinklonne\MenuBuilder\Models\Menu
title: Menus
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'kevinklonne/menubuilder/menus/update/:id'
