name: Menus
form: $/kevinklonne/menubuilder/models/menu/fields.yaml
modelClass: KevinKlonne\MenuBuilder\Models\Menu
defaultRedirect: kevinklonne/menubuilder/menus
create:
    redirect: 'kevinklonne/menubuilder/menus/update/:id'
    redirectClose: kevinklonne/menubuilder/menus
update:
    redirect: kevinklonne/menubuilder/menus
    redirectClose: kevinklonne/menubuilder/menus
